---
title: "Lasso - Ridge Regression Group for data science projects - Fall 2025"
subtitle: "A report on Lasso-Ridge Regression"
author: "Vijay Mohanam, Jennifer Nesbit and Sassou Khabou (Advisor: Dr. Cohen)"
date: '`r Sys.setenv(TZ = "America/New_York") format(Sys.Date(), "%Y-%m-%d")`'
format:
  html:
    code-fold: true
course: Capstone Projects in Data Science
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

Slides: [slides.html](slides.html){target="_blank"} ( Go to `slides.qmd`
to edit)

::: callout-note
**Week 01:** This is our first week as group, we are trying to compile a summary of introductions!

**Week 02:** We tried to add more articles from our research and narrowing on a particular dataset!

**Week 03:** Downloaded USA cancer dataset, exploring attributes and records for our study!

**Week 04:** Analysed the variables, selected and recoded for our model!

Nice effort!
:::

## Introduction

Least Absolute Shrinkage and Selection Operator (Lasso) and Ridge regression are both regularization techniques used to prevent overfitting and multicollinearity in linear regression models by adding a penalty term to the loss function. The Lasso regression method was first introduced by Tibshirani in 1996 and has become a widely used method in both statistical modeling and machine learning. Lasso regression uses L1 regularization, which adds a penalty proportional to the sum of the absolute values of the coefficients, whereas Ridge uses L2 regularization, which adds a penalty proportional to the sum of the squared coefficients. An additional regularization technique called Elastic Net regression, combines both Lasso and Ridge. This technique is useful when there are many correlated features. The L1 penalty used with Lasso shrinks some coefficients to zero which allows for automated selection while also reducing model complexity. Overall Lasso is able to combine both predictive accuracy with interpretability. 

Lasso has demonstrated its versatile and practical uses as it has been applied across diverse applications. In healthcare, Lasso has been used to predict prevalence of child malaria Aheto et al., 2021[@aheto], stroke risk in hypertensive patients Huang & Liu, 2025[@huang] and adverse drug reactions in polypharmacy Sommer et al., 2024 [@sommer]. These studies all highlight the ability for Lasso to produce models with fewer predictors while maintaining strong performance and often outperforming Ridge regression models in interpretability. Lasso has also been applied to clinical diagnostics, specifically improving disease classification for glaucoma progression Fujino et al., 2015 [@fujino] and differentiating between hematologic cancers Amaador et al., 2022[@amaador]. Another medical related paper on gastroenterology (Ali, H et al., 2023)[@ali] also applied Lasso to select key predictors and remove insignificant predictors by setting their coefficients to zero. These applications demonstrate the ability of Lasso to enhance decision making with streamlined models.

Lasso regression has also been proven as an effective methodology in economics and finance. Specifically, in predicting corporate bankruptcy Pereira et al., 2016[@pereira] and analyzing housing price network connectedness Gabauer et al., 2024[@gabauer]. Lasso has also been used for technology applications such as supporting innovations specifically with sensor selection for wearable respiratory monitoring devices Laufer et al., 2023 [@laufer] and improved interpretability with decision tree models Czajkowski et al., 2023 [@czajkowski].

Research has been done to compare the use of Lasso as a methodology to multiple related techniques such as Ridge and Elastic Net. Studies have shown that Ridge regression sometimes outperforms Lasso when predictor variables are highly correlated. However, Lasso tends to be more valuable when only a few predictors are significant and applicable to the problem at hand Vidaurre et al., 2013[@vidaurre]. Overall, Lasso shows a consistent advantage with its ability to produce sparse, interpretable and efficient models making it an excellent tool for both modeling and research.

A principal advantage of Lasso (Least Absolute Shrinkage and Selection Operator) regression is its capacity for feature shrinkage and selection. As established in the seminal works by “Introduction to the Lasso” (Gauraha, N, 2018)[@gauraha], selection of most relevant variables from a large set of clinical and pathological data while shrinking less important ones to zero(Li, Y., Bai. 2023)[@li] and “Regression Shrinkage and Selection Via the Lasso” (Robert Tibshirani. 1996)[@robert]. They also compare lasso regression to both ridge regression and subset selection. Unlike in ridge regression, where all parameters can only asymptotically approach zero, lasso regression allows some parameters to reach zero. These techniques are applied in Machine Learning for feature selection techniques in predictive modeling (R. Muthukrishnan and R. Rohini. 2016)[@muthu] .On the same lines, we can see how to handle zero inflated predictors(Mariella Gregorich et al., 2025)[@mari] handled by Lasso.

After considering the multiple impactful applications of Lasso regression, this study will apply Lasso to a real-world healthcare problem using the Surveillance, Epidemiology and End Results (SEER) database. Specifically, we aim to develop predictive models that will estimate the likelihood of various cancer treatments such as chemotherapy, radiation therapy or surgery based on patient demographics and clinical characteristics. We will leverage the ability of Lasso to select the most influential factors driving treatment decisions while automatically excluding less informative predictors. The ultimate goal of this application is to support utilization management processes by streamlining treatment approval pathways and expediting patient access to appropriate care. Through this study, we aim to demonstrate how Lasso regressive can serve as an effective tool for improving operational efficiency and decision making in oncology care.

*The final introduction paragraph on the problem that we will apply Lasso to will be added to draft next week after finalizing the problem and choosing a dataset.*

## Data Exploration and Visualization

We got the permission and downloaded cancer dataset of USA from https://seer.cancer.gov/.
It has about 240 attributes and ~10M records,

|Sl No|Attribute Name|Consider  |
|:------|:------ |:------------|
|1|Age recode with <1 year olds and 90+|  |
|2|Sex|  |
|3|Year of diagnosis|  |
|4|PRCDA 2020|  |
|5|Race recode (W, B, AI, API)|  |
|6|Origin recode NHIA (Hispanic, Non-Hisp)|  |
|7|Race and origin recode (NHW, NHB, NHAIAN, NHAPI, Hispanic)|  |
|8|Site recode ICD-O-3/WHO 2008|  |
|9|Behavior code ICD-O-3|  |
|10|TNM 7/CS v0204+ Schema (thru 2017)|  |
|11|TNM 7/CS v0204+ Schema recode|  |
|12|AYA site recode 2020 Revision|  |
|13|Lymphoid neoplasm recode 2021 Revision|  |
|14|ICCC site recode 3rd edition/IARC 2017|  |
|15|SEER Brain and CNS Recode|  |
|16|Site recode ICD-O-3 2023 Revision|  |
|17|Site recode ICD-O-3 2023 Revision Expanded|  |
|18|CS Schema - AJCC 6th Edition|  |
|19|Primary Site - labeled|  |
|20|Primary Site|  |
|21|Histologic Type ICD-O-3|  |
|22|Behavior recode for analysis|  |
|23|Grade Recode (thru 2017)|  |
|24|Derived Summary Grade 2018 (2018+)|  |
|25|Grade Clinical (2018+)|  |
|26|Grade Pathological (2018+)|  |
|27|Laterality|  |
|28|Diagnostic Confirmation|  |
|29|ICD-O-3 Hist/behav|  |
|30|ICD-O-3 Hist/behav, malignant|  |
|31|Histology recode - broad groupings|  |
|32|ICCC site recode extended 3rd edition/IARC 2017|  |
|33|Site recode ICD-O-3/WHO 2008 (for SIRs)|  |
|34|Schema ID (2018+)|  |
|35|AJCC ID (2018+)|  |
|36|EOD Schema ID Recode (2010+)|  |
|37|Site recode - rare tumors|  |
|38|Combined Summary Stage with Expanded Regional Codes (2004+)|  |
|39|Summary stage 2000 (1998-2017)|  |
|40|SEER historic stage A (1973-2015)|  |
|41|Derived EOD 2018 T Recode (2018+)|  |
|42|Derived EOD 2018 N Recode (2018+)|  |
|43|Derived EOD 2018 M Recode (2018+)|  |
|44|Derived EOD 2018 Stage Group Recode (2018+)|  |
|45|Derived AJCC Stage Group, 7th ed (2010-2015)|  |
|46|Derived AJCC T, 7th ed (2010-2015)|  |
|47|Derived AJCC N, 7th ed (2010-2015)|  |
|48|Derived AJCC M, 7th ed (2010-2015)|  |
|49|7th Edition Stage Group Recode (2016-2017)|  |
|50|Derived SEER Cmb Stg Grp (2016-2017)|  |
|51|Derived SEER Combined T (2016-2017)|  |
|52|Derived SEER Combined N (2016-2017)|  |
|53|Derived SEER Combined M (2016-2017)|  |
|54|Derived SEER Combined T Src (2016-2017)|  |
|55|Derived SEER Combined N Src (2016-2017)|  |
|56|Derived SEER Combined M Src (2016-2017)|  |
|57|Derived AJCC Stage Group, 6th ed (2004-2015)|  |
|58|Breast - Adjusted AJCC 6th Stage (1988-2015)|  |
|59|Derived AJCC T, 6th ed (2004-2015)|  |
|60|Derived AJCC N, 6th ed (2004-2015)|  |
|61|Derived AJCC M, 6th ed (2004-2015)|  |
|62|Breast - Adjusted AJCC 6th T (1988-2015)|  |
|63|Breast - Adjusted AJCC 6th N (1988-2015)|  |
|64|Breast - Adjusted AJCC 6th M (1988-2015)|  |
|65|Lymphoma - Ann Arbor Stage (1983-2015)|  |
|66|AJCC stage 3rd edition (1988-2003)|  |
|67|SEER modified AJCC stage 3rd (1988-2003)|  |
|68|T value - based on AJCC 3rd (1988-2003)|  |
|69|N value - based on AJCC 3rd (1988-2003)|  |
|70|M value - based on AJCC 3rd (1988-2003)|  |
|71|TNM Edition Number (2016-2017)|  |
|72|RX Summ--Surg Prim Site (1998+)|  |
|73|RX Summ--Scope Reg LN Sur (2003+)|  |
|74|RX Summ--Surg Oth Reg/Dis (2003+)|  |
|75|RX Summ--Surg/Rad Seq|  |
|76|Reason no cancer-directed surgery|  |
|77|Radiation recode|  |
|78|Chemotherapy recode (yes, no/unk)|  |
|79|Scope of reg lymph nd surg (1998-2002)|  |
|80|RX Summ--Reg LN Examined (1998-2002)|  |
|81|Surgery of oth reg/dis sites (1998-2002)|  |
|82|Site specific surgery (1973-1997 varying detail by year and site)|  |
|83|Radiation to Brain or CNS Recode (1988-1997)|  |
|84|RX Summ--Systemic/Sur Seq (2007+)|  |
|85|Time from diagnosis to treatment in days recode|  |
|86|Breslow Tumor Thickness (2018+)|  |
|87|PSA (Prostatic Specific Antigen) Lab Value (2018+)|  |
|88|Brain Molecular Markers (2018+)|  |
|89|AFP Post-Orchiectomy Lab Value Recode (2010+)|  |
|90|AFP Pretreatment Interpretation Recode (2010+)|  |
|91|B Symptoms Recode (2010+)|  |
|92|Breslow Thickness Recode (2010+)|  |
|93|CA-125 Pretreatment Interpretation Recode (2010+)|  |
|94|CEA Pretreatment Interpretation Recode (2010+)|  |
|95|Chromosome 19q: Loss of Heterozygosity (LOH) Recode (2010+)|  |
|96|Chromosome 1p: Loss of Heterozygosity (LOH) Recode (2010+)|  |
|97|Fibrosis Score Recode (2010+)|  |
|98|Gestational Trophoblastic Prognostic Scoring Index Recode (2010+)|  |
|99|Gleason Patterns Clinical Recode (2010+)|  |
|100|Gleason Patterns Pathological Recode (2010+)|  |
|101|Gleason Score Clinical Recode (2010+)|  |
|102|Gleason Score Pathological Recode (2010+)|  |
|103|hCG Post-Orchiectomy Range Recode (2010+)|  |
|104|Invasion Beyond Capsule Recode (2010+)|  |
|105|Ipsilateral Adrenal Gland Involvement Recode (2010+)|  |
|106|LDH Post-Orchiectomy Range Recode (2010+)|  |
|107|LDH Pretreatment Level Recode (2010+)|  |
|108|LN Head and Neck Levels I-III Recode (2010+)|  |
|109|LN Head and Neck Levels IV-V Recode (2010+)|  |
|110|LN Head and Neck Levels VI-VII Recode (2010+)|  |
|111|LN Head and Neck Other Recode (2010+)|  |
|112|LN Positive Axillary Level I-II Recode (2010+)|  |
|113|Lymph Node Size Recode (2010+)|  |
|114|Major Vein Involvement Recode (2010+)|  |
|115|Measured Basal Diameter Recode (2010+)|  |
|116|Measured Thickness Recode (2010+)|  |
|117|Mitotic Rate Melanoma Recode (2010+)|  |
|118|Multiple Myeloma Terminology Recode (2012+)|  |
|119|Number of Cores Positive Recode (2010+)|  |
|120|Number of Cores Examined Recode (2010+)|  |
|121|Number of Examined Para-Aortic Nodes Recode (2010+)|  |
|122|Number of Examined Pelvic Nodes Recode (2010+)|  |
|123|Number of Positive Para-Aortic Nodes Recode (2010+)|  |
|124|Number of Positive Pelvic Nodes Recode (2010+)|  |
|125|Perineural Invasion Recode (2010+)|  |
|126|Peripheral Blood Involvement Recode (2010+)|  |
|127|Peritoneal Cytology Recode (2010+)|  |
|128|Pleural Effusion Recode (2010+)|  |
|129|PSA Lab Value Recode (2010+)|  |
|130|Residual Tumor Volume Post Cytoreduction Recode (2010+)|  |
|131|Response to Neoadjuvant Therapy Recode (2010+)|  |
|132|Sarcomatoid Features Recode (2010+)|  |
|133|Separate Tumor Nodules Ipsilateral Lung Recode (2010+)|  |
|134|Tumor Deposits Recode (2010+)|  |
|135|Ulceration Recode (2010+)|  |
|136|Visceral and Parietal Pleural Invasion Recode (2010+)|  |
|137|EOD Primary Tumor Recode (2018+)|  |
|138|EOD Regional Nodes Recode (2018+)|  |
|139|EOD Mets Recode (2018+)|  |
|140|Prostate Pathological Extension (2018+)|  |
|141|Sentinel Lymph Nodes Examined (2018+)|  |
|142|Sentinel Lymph Nodes Positive (2018+)|  |
|143|Tumor Size Over Time Recode (1988+)|  |
|144|Tumor Size Summary (2016+)|  |
|145|Regional nodes examined (1988+)|  |
|146|Regional nodes positive (1988+)|  |
|147|SEER Combined Mets at DX-bone (2010+)|  |
|148|SEER Combined Mets at DX-brain (2010+)|  |
|149|SEER Combined Mets at DX-liver (2010+)|  |
|150|SEER Combined Mets at DX-lung (2010+)|  |
|151|Mets at DX-Distant LN (2016+)|  |
|152|Mets at DX-Other (2016+)|  |
|153|Breast Subtype (2010+)|  |
|154|ER Status Recode Breast Cancer (1990+)|  |
|155|PR Status Recode Breast Cancer (1990+)|  |
|156|Derived HER2 Recode (2010+)|  |
|157|Lymph-vascular Invasion (2004+ varying by schema)|  |
|158|CS tumor size (2004-2015)|  |
|159|CS extension (2004-2015)|  |
|160|CS lymph nodes (2004-2015)|  |
|161|CS mets at dx (2004-2015)|  |
|162|CS Tumor Size/Ext Eval (2004-2015)|  |
|163|CS Reg Node Eval (2004-2015)|  |
|164|CS Mets Eval (2004-2015)|  |
|165|CS site-specific factor 1 (2004-2017 varying by schema)|  |
|166|CS site-specific factor 2 (2004-2017 varying by schema)|  |
|167|CS site-specific factor 3 (2004-2017 varying by schema)|  |
|168|CS site-specific factor 4 (2004-2017 varying by schema)|  |
|169|CS site-specific factor 5 (2004-2017 varying by schema)|  |
|170|CS site-specific factor 6 (2004-2017 varying by schema)|  |
|171|Adjusted CS site-specific factor 7 (2004-2017 varying by schema)|  |
|172|CS site-specific factor 8 (2004-2017 varying by schema)|  |
|173|CS site-specific factor 9 (2004-2017 varying by schema)|  |
|174|CS site-specific factor 10 (2004-2017 varying by schema)|  |
|175|CS site-specific factor 11 (2004-2017 varying by schema)|  |
|176|CS site-specific factor 12 (2004-2017 varying by schema)|  |
|177|CS site-specific factor 13 (2004-2017 varying by schema)|  |
|178|CS site-specific factor 15 (2004-2017 varying by schema)|  |
|179|CS site-specific factor 16 (2004-2017 varying by schema)|  |
|180|CS site-specific factor 25 (2004-2017 varying by schema)|  |
|181|CS version input current (2004-2015)|  |
|182|CS version input original (2004-2015)|  |
|183|CS version derived (2004-2015)|  |
|184|Estrogen Receptor Summary (2018+)|  |
|185|HER2 Overall Summary Recode (2018+)|  |
|186|Progesterone Receptor Summary (2018+)|  |
|187|EOD 10 - Prostate path ext (1995-2003)|  |
|188|EOD 10 - extent (1988-2003)|  |
|189|EOD 10 - nodes (1988-2003)|  |
|190|EOD 10 - size (1988-2003)|  |
|191|Tumor marker 1 (1990-2003)|  |
|192|Tumor marker 2 (1990-2003)|  |
|193|Tumor marker 3 (1998-2003)|  |
|194|Coding system-EOD (1973-2003)|  |
|195|2-Digit NS EOD part 1 (1973-1982)|  |
|196|2-Digit NS EOD part 2 (1973-1982)|  |
|197|2-Digit SS EOD part 1 (1973-1982)|  |
|198|2-Digit SS EOD part 2 (1973-1982)|  |
|199|Expanded EOD(1) - CP53 (1973-1982)|  |
|200|Expanded EOD(2) - CP54 (1973-1982)|  |
|201|Expanded EOD(1,2) - CP53,54 (1973-1982)|  |
|202|Expanded EOD(3) - CP55 (1973-1982)|  |
|203|Expanded EOD(4) - CP56 (1973-1982)|  |
|204|Expanded EOD(5) - CP57 (1973-1982)|  |
|205|Expanded EOD(6) - CP58 (1973-1982)|  |
|206|Expanded EOD(7) - CP59 (1973-1982)|  |
|207|Expanded EOD(8) - CP60 (1973-1982)|  |
|208|Expanded EOD(9) - CP61 (1973-1982)|  |
|209|Expanded EOD(10) - CP62 (1973-1982)|  |
|210|Expanded EOD(11) - CP63 (1973-1982)|  |
|211|Expanded EOD(12) - CP64 (1973-1982)|  |
|212|Expanded EOD(13) - CP65 (1973-1982)|  |
|213|EOD 4 - extent (1983-1987)|  |
|214|EOD 4 - nodes (1983-1987)|  |
|215|EOD 4 - size (1983-1987)|  |
|216|COD to site recode|  |
|217|SEER cause-specific death classification|  |
|218|SEER other cause of death classification|  |
|219|Survival months|  |
|220|Survival months flag|  |
|221|COD to site rec KM|  |
|222|COD to site recode ICD-O-3 2023 Revision|  |
|223|COD to site recode ICD-O-3 2023 Revision Expanded (1999+)|  |
|224|Vital status recode (study cutoff used)|  |
|225|Sequence number|  |
|226|First malignant primary indicator|  |
|227|Primary by international rules|  |
|228|Record number recode|  |
|229|Total number of in situ/malignant tumors for patient|  |
|230|Total number of benign/borderline tumors for patient|  |
|231|Age recode with <1 year olds|  |
|232|Race recode (White, Black, Other)|  |
|233|Age recode with single ages and 85+|  |
|234|Age recode with single ages and 90+|  |
|235|Race recode (with detailed Asian and Native Hawaiian other PI)|  |
|236|Year of follow-up recode|  |
|237|Patient ID|  |
|238|Type of Reporting Source|  |
|239|Marital status at diagnosis|  |
|240|CoC Accredited Flag (2018+)|  |
|241|Median household income inflation adj to 2023|  |
|242|Rural-Urban Continuum Code|  |


The data for this study was obtained from the SEER program of the [National Cancer Institute (NCI)](https://seer.cancer.gov/archive/manuals/2018/SPCSM_2018_maindoc.pdf). SEER is a comprehensive population-based cancer registry within the United States that consists of a collection of detailed information on cancer incidence, patient demographics, tumor characteristics, treatment modalities and survival outcomes. The SEER dataset provides high quality, standardized data that allows for large-scale analyses of cancer patterns, treatments and outcomes across diverse populations in the United States. For this study we focused on female breast cancer cases (ICD O-3 site codes C50.0 - C50.9) from 2018 - 2021 and specific variables to indicate whether a patient received specific treatment such as surgery, radiation, chemotherapy, immunotherapy or hormone therapy based on the SEER treatment summary fields. This time period aligns with the period following SEER’s transition to the Extent of Disease (EOD) 2018 and Summary Stage 2018 systems. This time was chosen because these years provide the most consistent and comprehensive recording of tumor stage, biological markers and treatment variables. Using 2018 - 2021 ensures compatibility across staging and treatment codes while avoiding inconsistencies in earlier datasets.

We focused on variables that are clinically relevant and have been shown to influence treatment decisions in breast cancer. These variables have been categorized into three groups: treatment variables, tumor characteristics and patient demographics. Surgical treatment was identified using the variable **RX Sum–Surg Prim Site**, radiation therapy from **Phase I, II and III Radiation Treatment Modality**, chemotherapy from **RX Summ–Chemo**, hormone therapy from **RX Summ–Hormone** and immunotherapy from **RX Summ–BRM**. These variables capture first-course treatments administered after diagnosis. Only first primary malignancies were included to avoid confounding from prior cancer diagnoses and treatments **(Sequence number = 00, 01)**. Patients with missing or unknown treatment or key staging information were excluded. Each treatment variable was recoded into a binary outcome with 1 indicating that treatment was received and 0 indicating that treatment was not received. 


Table 1

***Treatment Variables***

|Veritable Name|Description|Seer Codes (2018-2022)|Recoding for modeling|
|:------|:------ |:------------|:------------|
|RX Summ–Surg Prim Site|Surgery of the primary site|00 = None; no surgical procedure of primary site; diagnosed at autopsy only 10-19 = Site-specific codes. Tumor destruction; no pathologic specimen or unknown whether there is a pathologic specimen<BR>20-80 = Site-specific codes. Resection; pathologic specimen 90 = Surgery, NOS. A surgical procedure to the primary site was done, but no information on the type of surgical procedure is provided.<BR>98 = Special codes for hematopoietic neoplasms; ill-defined sites; and unknown primaries (See site-specific codes for the sites and histologies), except death certificate only<BR>99 = Unknown if surgery performed|Binary:<br> 1 = any surgery (10-80, 90)<BR> 0 = no surgery (00)<BR> exclude other/unknown (98, 99)|
|Phase I Radiation Treatment Modality<BR><BR>Phase II Radiation Treatment Modality<BR><BR>Phase III Radiation Treatment Modality|The radiation modality administered during the first, second and third phase of radiation treatment delivered during the first course of treatment.|00 = No radiation treatment<BR>01 = External beam, NOS<BR>02 = External beam, photons<BR>03 = External beam, protons<BR>04 = External beam, electrons<BR>05 = External beam, neutrons<BR>06 = External beam, carbon ions<BR>07 = Brachytherapy, NOS<BR>08 = Brachytherapy, intracavitary, LDR<BR>09 = Brachytherapy, intracavitary, HDR<BR>10 = Brachytherapy, Interstitial, LDR<BR>11 = Brachytherapy, Interstitial, HDR<BR>12 = Brachytherapy, electronic<BR>13 = Radioisotopes, NOS<BR>14 = Radioisotopes, Radium-232<BR>15 = Radioisotopes, Strontium-89<BR>16 = Radioisotopes, Strontium-90<BR>99 = Treatment radiation modality unknown; Unknown if radiation treatment administered|Binary: <BR>1 = any radiation (01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12, 13, 14, 15, 16)<BR>0 = no radiation (00)<BR> exclude unknown (99)|
|RX Summ–Chemo|The chemotherapy given as a part of the first course of treatment or the reason that chemotherapy was not given.|00 = None, chemotherapy was not part of the planned first course of therapy; diagnosed at autopsy<BR>01 Chemotherapy administered as first course therapy, but the type and number of agents is not documented in the patient record<BR>02 = Single agent chemotherapy administered as first course therapy<BR>03 = Multi-agent chemotherapy administered as first course therapy<BR>82 = Chemotherapy was not recommended/administered because it was contraindicated due to patient<BR>risk factors (comorbid conditions, advanced age, etc.)<BR>85 = Chemotherapy was not administered because the patient died prior to planned or recommended therapy<BR>86 = Chemotherapy was not administered. It was recommended by the patient’s physician but was not administered as part of the first course of therapy. No reason was stated in patient record.<BR>87 = Chemotherapy was not administered. It was recommended by the patient’s physician, but the treatment was refused by the patient, a patient’s family member, or the patient’s guardian. The refusal was noted in the patient record.<BR>88 = Chemotherapy was recommended, but it is unknown if it was administered<BR>99 = It is unknown whether a chemotherapeutic agent(s) was recommended or administered because it is not stated in the patient record|Binary: <BR>1 = any chemotherapy(01, 02, 03)<BR>0 = no chemotherapy (00)<BR>exclude other/unknown (82, 85, 86, 87, 88, 99)|
|RX Summ--Hormone|Records therapy administered as first course treatment that affects cancer tissue by adding, blocking, or removing the action or production of hormones.|00 = None, hormone therapy was not part of the planned first course of therapy; not usually administered for this type and/or stage of cancer; diagnosed at autopsy only <BR>01 = Hormone therapy administered as first course therapy<BR>82 = Hormone therapy was not recommended/administered because it was contraindicated due to patient risk factors (comorbid conditions, advanced age, etc.)<BR>85 = Hormone therapy was not administered because the patient died prior to planned or recommended therapy<BR>86 = Hormone therapy was not administered. It was recommended by the patient’s physician but was not administered as part of the first course of therapy. No reason was stated in the patient record.<BR>87 = Hormone therapy was not administered. It was recommended by the patient’s physician, but this treatment was refused by the patient, a patient’s family member, or the patient’s guardian. The refusal was noted in the patient record.<BR>88 = Hormone therapy was recommended, but it is unknown if it was administered<BR>99 = It is unknown whether a hormonal agent(s) was recommended or administered|Binary: <BR>1 = hormone therapy received (01)<BR>0 = no hormone therapy received (00)<BR>exclude other unknown (82, 85, 86, 87, 88, 99)|
|RX Summ–BRM|Records immunotherapeutic (biological therapy, biotherapy or biological response modifier) agents administered as first course of therapy.|00 = None, immunotherapy was not part of the planned first course of therapy<BR>01 = Immunotherapy was administered as first course therapy<BR>82 = Immunotherapy was not recommended/administered because it was contraindicated due to patient risk factors (comorbid conditions, advanced age, etc.)<BR>85 = Immunotherapy was not administered because the patient died prior to planned or recommended therapy<BR>86 = Immunotherapy was not administered; it was recommended by the patient’s physician but was not administered as part of the first-course of therapy. No reason was noted in the patient’s record.<BR> 87 = Immunotherapy was not administered. It was recommended by the patient’s physician, but this treatment was refused by the patient, a patient’s family member, or the patient’s guardian. The refusal was noted in the patient record.<BR> 88 = Immunotherapy was recommended, but it is unknown if it was administered<BR>99 = It is unknown if immunotherapy was recommended or administered because it is not stated in patient record.|Binary: <BR>1 = immunotherapy received (01)<BR>0 = no immunotherapy therapy received (00)<BR>exclude other unknown (82, 85, 86, 87, 88, 99)|
|Sequence Number–Central|Describes the number and sequence of all reportable malignant, in situ, benign, and borderline primary tumors that occur over the lifetime of a patient.|00 = One primary in the patient’s lifetime <BR>01 = First of two or more primaries<BR>02 = Second of two or more primaries|Filter data to only include 00 and 01|



Table 2

***Treatment Characteristics***

|Veritable Name|Description|Seer Codes (2018-2022)|Recoding for modeling|
|:------|:------ |:------------|:------------|
|Tumor Size Clinical|Size of a solid primary tumor before any treatment|000 = No mass/tumor found<BR>001 = 1 mm or described as less than 1 mm (0.1 cm or less than 0.1 cm)<BR>002-988 = Exact size in millimeters (2 mm to 988 mm) (0.2 to 98.8 cm)<BR>989 = 989 millimeters or larger (98.9 cm or larger)<BR>990 = Microscopic focus or foci only and no size of focus is given<BR>998 = Alternate descriptions of tumor size for specific sites:DiffuseBreast (C50.0-C50.6, C50.8-C50.9)<BR>999 = Unknown; size not stated Not documented in patient record Size of tumor cannot be assessed The only measurement(s) describes pieces or chips Not applicable|Continuous numeric <BR> unknowns excluded|
|EOD Regional Nodes|Regional lymph nodes involved with cancer at the time of diagnosis.|000 = None<BR>800 = Regional lymph node(s), NOS Lymph node(s), NOS<BR>888 = Not applicable–e.g., CNS, hematopoietic<BR>999 = Unknown|Binary: <BR>1 = positive lymph nodes (800)<BR>0 = no positive lymph nodes (000)<BR>exclude other/unknown (888, 999)|
|Mets at DX–Bone|This field identifies whether bone is an involved metastatic site.|0 = None; no bone metastases <BR>1 = Yes; distant bone metastases<BR>8 = Not applicable<BR>9 = Unknown whether bone is an involved metastatic site Not documented in patient record|Binary: <BR>1 = bone metastases (1)<BR>0 = no bone metastases (0)<BR> exclude n/a and unknown (8, 9)|
|Mets at DX-Brain|This field identifies whether brain is an involved metastatic site.|0 = None; no brain metastases <BR>1 = Yes; distant brain metastases<BR>8 = Not applicable<BR>9 = Unknown whether brain is involved metastatic site Not documented in patient record|Binary: <BR>1 = brain metastases (1)<BR>0 = no brain metastases (0)<BR>exclude n/a and unknown (8, 9)|
|Mets at DX-Liver|This field identifies whether liver is an involved metastatic site.|0 = None; no liver metastases <BR>1 = Yes; distant liver metastases<BR>8 = Not applicable<BR>9 = Unknown whether liver is involved metastatic site Not documented in patient record|Binary: <BR>1 = liver metastases (1)<BR>0 = no liver metastases (0)<BR> exclude n/a and unknown (8, 9)|
|Mets at DX-Lung|This field identifies whether lung is an involved metastatic site.|0 = None; no lung metastases <BR>1 = Yes; distant lung metastases<BR>8 = Not applicable<BR>9 = Unknown whether lung is involved metastatic site Not documented in patient record|Binary: <BR>1 = lung metastases (1)<BR>0 = no lung metastases (0)<BR> exclude n/a and unknown (8, 9)|
|Mets at DX-Distant LN|This field identifies whether distant lymph node(s) are an involved metastatic site.|0 = None; no distant lymph node metastases<BR>1 = Yes; distant lymph node metastases<BR>8 = Not applicable<BR>9 = Unknown whether distant lymph node(s) are involved metastatic site Not documented in patient record|Binary: <BR>1 = distant lymph node metastases (1)<BR>0 = no distant lymph node metastases (0)<BR> exclude n/a and unknown (8, 9)|
|Derived Summary Stage 2018||0 = In situ <BR>1 = Localized<BR>2 = Regional, direct extension only<BR>3 = Regional, regional lymph nodes only<BR>4 = Regional, direct extension and regional lymph nodes<BR>7 = Distant<BR>8 = Benign, borderline<BR>9 = Unknown if extension or metastasis (unstaged, unknown, or unspecified) Death certificate only case|Categorical: <BR>0 = In situ <BR>1 = Localized <BR>2 = Regional, direct extension only<BR>3 = Regional,regional lymph nodes only<BR>4 = Regional, direct extension and regional lymph nodes<BR>7 = Distant <BR>exclude 8, 9|
|Laterality||0 = Not a paired site <BR>1 = Right: origin of primary<BR>2 = Left: origin of primary <BR>3 = Only one side involved, right or left origin unspecified<BR>4 = Bilateral involvement at time of diagnosis, lateral origin unknown for a single primary; or both ovaries involved simultaneously, single histology; bilateral retinoblastomas; bilateral Wilms tumors<BR>5 = Paired site: midline tumor (effective with 01/01/2010 dx)<BR>9 = Paired site, but no information concerning laterality|Categorical:<BR>1 = Right (1)<BR>2 = Left (2)<BR>3 = Bilateral (4)<BR>4 = Midline (5)<BR>exclude unspecified/unknown (3, 9)<br>*exclude “not a paired site” breast is always paired (0)|
|Grade Clinical|Records the grade of a solid primary tumor before any treatment|1 = G1: Low combined histologic grade (favorable), SBR score of 3–5 points<BR>2 = G2: Intermediate combined histologic grade (moderately favorable); SBR score of 6–7 points<BR>3 = G3: High combined histologic grade (unfavorable); SBR score of 8–9 points|Categorical: <BR>1 = G1<BR>2 = G2<BR>3 = G3<BR>exclude unknown (9)|
|ER Summary|ER (Estrogen Receptor) Summary is a summary of results of the estrogen receptor (ER) assay.|0 = ER negative<BR>1 = ER positive<BR>7 = Test ordered, results not in chart<BR>9 = Not documented in medical record Cannot be determined (indeterminate) ER (Estrogen Receptor) Summary status not assessed or unknown if assessed|Binary: <BR>1 = ER positive (1)<BR>0 = ER negative (0)<BR>exclude n/a and unknown (7, 9)|
|PR Summary|PR (Progesterone Receptor) Summary is a summary of results from the progesterone receptor (PR) assay.|0 = PR negative (0.0% or less than 1%) <BR>1 = PR positive<BR>7 = Test ordered, results not in chart<BR>9 = Not documented in medical record Cannot be determined (indeterminate) PR (Progesterone Receptor) Summary status not assessed or unknown if assessed|Binary: <BR>1 = PR positive (1)<BR>0 = PR negative (0)<Br>exclude n/a and unknown (7, 9)|
|HER2 Overall Summary|HER2 Overall Summary is a summary of results from HER2 testing.|0 = HER2 negative; equivocal <BR>1 = HER2 positive<BR>7 = Test ordered, results not in chart<BR>8 = Not applicable: Information not collected for this case (If this item is required by your standard setter, use of code 8 will result in an edit error.)<BR>9 = Not documented in medical record Cannot be determined (indeterminate) HER2 Overall Summary status not assessed or unknown if assessed|Binary: <BR>1 = HER2 positive (1)<BR>0 = HER2 negative (0)<BR>exclude n/a and unknown (7, 8, 9)|



Table 3

***Patient Demographics***

|Veritable Name|Description|Seer Codes (2018-2022)|Recoding for modeling|
|:------|:------ |:------------|:------------|
|Age at Diagnosis|This data item represents the age of the patient at diagnosis for this cancer.|000 Less than one year old <BR>001 One year old, but less than two years old<BR>002 Two years old (Actual age in years) <BR>101 One hundred one years old <BR>120 One hundred twenty years old<BR>999 Unknown age||
|Race 1, Race 2, Race 3, Race 4, Race 5|The five race fields (Race 1 – Race 5) make it possible to code multiple races for one person, consistent with the 2000 Census.|01 White<BR>02 Black<BR>03 American Indian, Aleutian, Alaskan Native or Eskimo (includes all indigenous populations of the western hemisphere)<BR>04 Chinese<BR>05 Japanese<BR>06 Filipino<BR>07 Hawaiian<BR>08 Korean<BR>10 Vietnamese<BR>11 Laotian<BR>12 Hmong<Br>13 Kampuchean (including Khmer and Cambodian)<BR>14 Thai<BR>15 Asian Indian or Pakistani, NOS (Effective with 01/01/2010 dx)<BR>16 Asian Indian (Effective with 01/01/2010 dx)<BR>17 Pakistani (Effective with 01/01/2010 dx)<BR>20 Micronesian, NOS<BR>21 Chamorro/Chamoru<BR>22 Guamanian, NOS<BR>25 Polynesian, NOS<BR>26 Tahitian<BR>27 Samoan<BR>28 Tongan<BR>30 Melanesian, NOS<BR>31 Fiji Islander<BR>32 New Guinean<BR>88 No additional races (Race 2 – Race 5)<BR>96 Other Asian, including Asian, NOS and Oriental, NOS<BR>97 Pacific Islander, NOS<BR>98 Other<BR>99 Unknown||
|Marital Status at DX|Patient’s marital status at the time of diagnosis for the reportable tumor.|1 Single (never married)<BR>2 Married (including common law)<BR>3 Separated<BR>4 Divorced<BR>5 Widowed<BR>6 Unmarried or Domestic Partner (same sex or opposite sex, registered or unregistered, other than common law marriage) (effective for cases diagnosed 01/01/11 and forward)<BR>9 Unknown||
|Primary Payer at DX|Identifies the patient’s primary health insurance carrier or method of payment at the time of initial diagnosis and/or treatment.|01 Not insured Patient has no insurance and is declared a charity write-off<BR>02 Not insured, self-pay Patient has no insurance and is declared responsible for charges<BR>10 Insurance, NOS Type of insurance is unknown or other than types listed in codes 20, 21,31, 35, 60-68<BR>20 Private Insurance:Managed care, HMO,or PPO An organized system of prepaid care for a group of enrollees usually within a defined geographic area. Generally formed as one of four types: a group model, an independent physician association (IPA), a network, or a staff model. “Gate-keeper model” is another term for describing this type of insurance.<BR>21 Private Insurance: Fee-for-service An insurance plan that does not have negotiated fee structure with the participating hospital. Type of insurance plan not coded as 20.<BR>31 Medicaid State government administered insurance for persons who are uninsured, below the poverty level, or covered under entitlement programs Medicaid other than Medicaid described in code 35<BR>35 Medicaid – administered through a Managed Care plan Patient is enrolled in Medicaid through a Managed Care program (e.g., HMO or PPO). The managed care plan pays for all incurred costs.<BR>60 Medicare/Medicare,NOS Federal government funded insurance for persons who are 62 years of age or older, or are chronically disabled (social security insurance eligible). Includes Medicare without supplement. Not described in codes 61, 62, or 63.<BR>61 Medicare with supplement, NOS Patient has Medicare and another type of unspecified insurance to pay costs not covered by Medicare. (See also, codes 63 and 64.)<BR>62 Medicare – Administered through a Managed Care Plan Patient is enrolled in Medicare through a Managed Care plan (e.g., HMO or PPO). The Managed Care plan pays for all incurred costs. <BR>63 Medicare with private supplement Patient has Medicare and private insurance to pay costs not covered by Medicare.<BR>64 Medicare with Medicaid eligibility Federal government Medicare insurance with state-administered Medicaid supplement.<BR>65 TRICARE Department of Defense program providing supplementary civilian- sector hospital and medical services beyond a military treatment facility to military dependents, retirees, and their dependents Formerly known as CHAMPUS (Civilian Health and Medical Program of the Uniformed Services).<BR>66 Military Military personnel or their dependents treated at a military facility<BR>67 Veterans Affairs Veterans treated in Department of Veterans Affairs facilities <BR>68 Indian/Public Health Service Patient receives care at an Indian Health Service facility or at another facility and medical costs are reimbursed by the Indian Health Service Patient receives care at a Public Health Service facility or at another facility, and medical costs are reimbursed by the Public Health Service Section III: Demographic Information 76SEER Program Coding and Staging Manual 2018 Code Label Definition<BR>99 Insurance status unknown Patient’s medical record does not indicate whether or not the patient is insured||


Only female breast cancer cases (C50.0–C50.9) diagnosed from 2018–2021 were included.
First primary malignancies only (Sequence Number = 00 or 01).
Cases with missing or unknown treatment or key staging variables were excluded.
Variables were recoded into consistent binary or continuous formats suitable for Lasso logistic regression modeling.


## Methods



## Analysis and Results





## Modeling and Results


## Conclusion


## References

